name: Build and Deploy

on: [push, pull_request]

jobs:
    job1:
        environment: 
            name: testing
        runs-on: ubuntu-latest

        # Global env variables for the job
        env:
            DATABASE_HOSTNAME : ${{ secrets.DATABASE_HOSTNAME }}
            DATABASE_PORT : ${{ secrets.DATABASE_PORT }}
            DATABASE_PASSWORD : ${{ secrets.DATABASE_PASSWORD }}
            DATABASE_NAME : ${{ secrets.DATABASE_NAME }}
            DATABASE_USERNAME : ${{ secrets.DATABASE_USERNAME }}
            SECRET_KEY : ${{ secrets.SECRET_KEY }}
            ALGORITHM : ${{ secrets.ALGORITHM }}
            ACCESS_TOKEN_EXPIRE_MINUTES : ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
                    # This creates the DB with the _test suffix
                    POSTGRES_DB: ${{ secrets.DATABASE_NAME }}_test
                ports:
                - 5432:5432
                options: >-
                    --health-cmd "pg_isready -U postgres"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: pulling git repo
              uses: actions/checkout@v2

            - name: install python version 3.12
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            - name: update pip
              run: python -m pip install --upgrade pip

            - name: install dependencies
              run: pip install -r requirements.txt

            - name: run tests with pytest
              env:
                # OVERRIDE: Tell the app to look for the _test database
                DATABASE_NAME: ${{ secrets.DATABASE_NAME }}_test
                # OVERRIDE: Ensure the app talks to the local service container
                DATABASE_HOSTNAME: localhost
              run: |
                pip install pytest
                pytest