name: build and deploy code

on: [push, pull_request]

jobs:
    job1:
        environment:
            name: testing
        env:
            DATABASE_HOSTNAME: ${{Secrets.DATABASE_HOSTNAME}}
            DATABASE_PORT: ${{Secrets.DATABASE_PORT}}
            DATABASE_PASSWORD: ${{Secrets.DATABASE_PASSWORD}}
            DATABASE_NAME: ${{Secrets.DATABASE_NAME}}
            DATABASE_USERNAME: ${{Secrets.DATABASE_USERNAME}}
            SECRET_KEY: ${{Secrets.SECRET_KEY}}
            ALGORITHM: ${{Secrets.ALGORITHM}}
            ACCESS_TOKEN_EXPIRE_MINUTES: ${{Secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: ${{Secrets.DATABASE_PASSWORD}}
                    POSTGRES_DB: ${{Secrets.DATABASE_NAME}}_test
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retires 5
        
        runs-on: ubuntu-latest
        steps:
            - name: pilling git repo
              uses: action/checkout@v2
            - name: install python vesion 3.9
              uses: actions/setup-python@v2
              with:
                python-version: "3.9"
            - name: update pip
              run: python -m pip install --upgrade pip
            - name: install all dpendencies
              run: pip install -r requirements
            - name: test with pytest
              run: pytest

